---
apiVersion: v1
kind: Namespace
metadata: 
  name: fortune-ns
  labels: 
    app: fortune
    version: v1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
  namespace: fortune-ns
  labels:
    app : fortune 

spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: fortune-pod
      
  template: 
    metadata:
      name: fortune-pod
      labels: 
        app: fortune-pod
    spec:
      containers:
      - name: fortune-container
        image: chukmunnlee/fortune:v1
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 3000
