---
apiVersion: v1
kind: Namespace
metadata: 
  name: nw
  labels: 
    app: nwdb
    version: v1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwdb-deploy
  namespace: nw
  labels:
    app : nwdb 

spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: nwdb-pod
      
  template: 
    metadata:
      name: nwdb-pod
      labels: 
        app: nwdb-pod
    spec: 
      containers:
      - name: nwdb-container
        image: hamsterboyboy/my-db:v3
        imagePullPolicy: IfNotPresent
        ports: 
        - name: for-port
          containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: nwdb-svc
  namespace: nw
  labels:
    app : nwdb

spec:
  type: ClusterIP
  selector:
    app: nwdb-pod
  ports: 
  - port: 3306
    targetPort: for-port